
import os
import distutils.sysconfig
Import( 'env' )

Import( 'qpsnrLib' )
Import( 'qpsnrLibStatic' )

qpsnrApp = env.Program(
	'qpsnr',
	Glob( '*.cpp' ),
	LIBS = [
		qpsnrLib,
		"avutil",
		"avformat",
		"avcodec",
	]
)

installApp = env.Install( "bin", [ qpsnrApp ] )

env.Alias( "install", installApp )
env.Depends( installApp, qpsnrApp )
