
Import( 'env' )

conf = Configure(env)
if not conf.CheckLibWithHeader('avutil', 'libavutil/avutil.h', 'c'):
    print 'Did not find libavutil.a or avutil.lib, exiting!'
    Exit(1)

if not conf.CheckLibWithHeader('avcodec', 'libavcodec/avcodec.h', 'c'):
    print 'Did not find libavcodec.a or avcodec.lib, exiting!'
    Exit(1)

if not conf.CheckLibWithHeader('avformat', 'libavformat/avformat.h', 'c'):
    print 'Did not find libavformat.a or avformat.lib, exiting!'
    Exit(1)

env = conf.Finish()

qpsnrLib = env.SharedLibrary(
    'qpsnr',
    Glob( '*.cpp' ),
    LIBS = [
    	"avutil",
    	"avcodec",
    	"avformat",
    ],
)

qpsnrLibStatic = env.StaticLibrary(
    'qpsnr',
    Glob( '*.cpp' ),
    LIBS = [
    	"avutil",
    	"avcodec",
    	"avformat",
    ],
)

env.Alias( 'install', env.InstallVersionedLib( 'lib', qpsnrLib ) )
env.Alias( 'install', env.Install( 'lib', qpsnrLibStatic ) )

Export( 'qpsnrLib' )
Export( 'qpsnrLibStatic' )
